version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: gym_mysql
    restart: always
    env_file:
      - hellofx/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: gym_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: gym_mysql_data
